name = "Esli Silva"
description = "SRE | DevOps | SysAdmin"
keywords = "Esli Silva"
image = "new-profile.jpg"
theme = "dark"
primary_color = "#93c47d"
text_align = "center"
#gtag_id = "G- "
base_url = "https://esli.cafe"

[[sections]]
title = "Perfil"
description = "desc"
direction = "column"
item_style = "outline"
#[[sections.items]]
#embed_url = "https://www.youtube.com/embed/xxx-xyz"
[[sections.items]]
title = "Blog"
description = "meus artigos, estudos e paginas"
url = "https://esli.blog"
[[sections.items]]
title = "notas"
description = "Alguns pensamentos e ideias no bullet journal"
url = "https://listed.to/@Esli"
[[sections.items]]
title = "linkedin"
description = "alguém tem que trabalhar né?"
url = "https://linkedin.com/en"


[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/github/ffffff"
title = "github"
url = "https://github.com/Esl1h"
[[sections.items]]
icon = "https://cdn.simpleicons.org/git/ffffff"
title = "Others Git"
url = "https://esli.blog"
[[sections.items]]
icon = "https://cdn.simpleicons.org/stackoverflow/ffffff"
title = "stackoverflow"
url = "https://stackoverflow.com/user"
[[sections.items]]
title = "tips"
icon = "https://cdn.simpleicons.org/bitcoin/ffffff"
url = "https://listed.to/@Esli/tip"
