name = "xxx xyz"
description = "Desc"
keywords = "xxx xyz desc keys"
image = "new-profile.jpg"
theme = "dark"
primary_color = "#93c47d"
text_align = "center"
gtag_id = "G- "
base_url = "https://https://esl1h.github.io"

[[sections]]
title = "TT"
description = "desc"
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/xxx-xyz"
[[sections.items]]
title = "t1"
description = "desc1"
url = "https://www.imdb.com/title/xxx-xyz/"
[[sections.items]]
title = "t2"
description = "desc2"
url = "https://www.imdb.com/title/xxx-xyz/"
[[sections.items]]
title = "t3"
description = "desc3"
url = "https://www.imdb.com/title/xxx-xyz/"


[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/xxx-xyz"
[[sections.items]]
icon = "https://cdn.simpleicons.org/imdb/ffffff"
title = "IMDb"
url = "https://www.imdb.com/name/xxx-xyz/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/wikipedia/ffffff"
title = "Wikipedia"
url = "https://en.wikipedia.org/wiki/xxx-xyz"
[[sections.items]]
title = "Rotten Tomatoes"
icon = "https://cdn.simpleicons.org/rottentomatoes/ffffff"
url = "https://www.rottentomatoes.com/celebrity/xxx-xyz"
