name = "Esli Silva"
description = " SRE | DevOps | SysAdmin | 🕎 🐧 💻 🥋 אצלי "
keywords = "Esli Silva"
image = "new-profile.jpg"
theme = "dark"
primary_color = "#38761d"
text_align = "center"
#gtag_id = "G- "
base_url = "https://esli.cafe"

[[sections]]
title = "Main websites"
description = "My main addresses where you'll find my latest content here. Always up for a coffee ☕ and chat. Portuguese | English and (not so well) Spanish"
direction = "column"
item_style = "outline"

#[[sections.items]]
#embed_url = "https://www.youtube.com/embed/xxx-xyz"
#embed_url = "https://pbs.twimg.com/profile_banners/139572785/1584591802/1500x500"

[[sections.items]]
title = "Blog"
description = "My articles, blogging and website"
url = "https://esli.blog"

[[sections.items]]
title = "Notes"
description = "Some quick notes, thoughts, and ideas in the bullet journal"
url = "https://listed.to/@Esli"

[[sections.items]]
title = "LinkedIn"
description = "Profile / resume / curriculo"
url = "https://www.linkedin.com/in/eslih/?locale=en_US"

[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"

[[sections.items]]
icon = "https://cdn.simpleicons.org/keybase/ffffff"
title = "keybase"
url = "https://keybase.io/esl1h"

[[sections.items]]
title = "hashnode"
icon = "https://cdn.simpleicons.org/hashnode/ffffff"
url = "https://hashnode.com/@esl1h"

[[sections.items]]
icon = "https://cdn.simpleicons.org/git/ffffff"
#title = "Git"
url = "https://listed.to/@Esli/64643/git"

[[sections.items]]
icon = "https://cdn.simpleicons.org/github/ffffff"
#title = "GitHub"
url = "https://github.com/Esl1h"

[[sections.items]]
#title = "tips"
icon = "https://cdn.simpleicons.org/bitcoin/ffffff"
url = "https://listed.to/@Esli/tip"

[[sections.items]]
icon = "https://cdn.simpleicons.org/stackoverflow/ffffff"
#title = "overflow"
url = "https://stackoverflow.com/users/4122311/esli-silva"

[[sections.items]]
#title = ""
icon = "https://cdn.simpleicons.org/x/ffffff"
url = "https://x.com/esl1h"

